### ISSUE TITLE
large scale values for NBI distribution

### ISSUE THREAD

**Issue by hrkadkhodaei** [StatMixedML/XGBoostLSS#12]
Hi,

Thank you for creating XGBoostLSS. 
I have a question, When I set the distribution to "NBI" (Negative Binomial) and make predictions for some samples, I see that the scale parameter is always the same for all samples and it is greater than zero (for example, 88). I suppose that for negative binomial, scale is equal to 1/n and because n>0 it should be less than 1 for most of the time. 

Do I have any misunderstanding on this?

**Comment by StatMixedML** [comment]
Closing this for now but feel free to re-open if the problem still persists.
