### ISSUE TITLE
Beta distribution - 0 log-likelihood, 'mean of empty string' message

### ISSUE THREAD

**Issue by dlewis-esure** [StatMixedML/XGBoostLSS#14]
Hello! Been exploring your package for a predictive modelling project, and think I've found an issue? Either that or I've missed something important I need to do, but either way it's not working. Basically, whenever I try to train a model using a beta distribution as the output, I get log-likelihoods of 0 every time. I've put reproducible code below, using the sklearn diabetes regression toy dataset as an example (alright, it's not a beta distribution, but it should still return something non-zero...). The problem doesn't occur with Gaussian distribution, and it occurs regardless of stabilisation method, and whether I'm using `train`, `cv` or `hyper_opt`, so it's not just a hyperparameter choice. During the training at some point you also get either a message saying `Mean of empty slice` or `All-NaN slice encountered`, so that probably points to the cause. I'm not entirely sure what's causing this, but it's probably an issue with the custom objective function? Could be the custom metrics, I suppose, but I think the objective function is more likely. 

Anyway, if you could take a look at it and let me know if I'm doing something wrong, or if there is something weird going on under the hood, that would be great! Thanks very much.

```
from sklearn.datasets import load_diabetes
from xgboostlss.model import xgboostlss
from xgboostlss.distributions import Beta, Gaussian
from xgboost import DMatrix

X, y = load_diabetes(return_X_y=True, as_frame=True)
train_x = X[:-50]
train_y = y[:-50]
test_x = X[-50:]
test_y = y[-50:]
dtrain = DMatrix(train_x, train_y)
dtest = DMatrix(test_x, test_y)

beta = Beta
beta.stabilize = "L2"

single_trial_params = {
    "eta": 0.01,                   
    "max_depth": 4,
    "gamma": 1,
    "subsample": 0.6,
    "colsample_bytree": 0.7,
    "min_child_weight": 1,
}

eval_results = {}
model = xgboostlss.train(
    params=single_trial_params,
    dtrain=dtrain,
    dist=beta,
    evals=[(dtrain, 'train'), (dtest, 'test')],
    evals_result=eval_results
)
```

**Comment by StatMixedML** [comment]
Hi @dlewis-esure,

thanks for your interest and the detailed MWE.

The Beta-Distribution is appropriate for, e.g., percentage values or more generally speaking for responses that are in (0,1). Checking your response, however, is far from this :-).

```python
y.describe()

count    442.000000
mean     152.133484
std       77.093005
min       25.000000
25%       87.000000
50%      140.500000
75%      211.500000
max      346.000000
Name: target, dtype: float64


pd.DataFrame(y).plot(kind='hist') 

![image](https://user-images.githubusercontent.com/41187941/157443964-a709f73d-d30c-4807-b6b1-d33b39a4d07d.png)

Since the data is outside (0,1) the Beta-Density cannot properly evaluate your response and the nll is not defined.

So I suggest you use another distribution that is more appropriate for the data.

**Comment by dlewis-esure** [comment]
Hi there - this was just a dummy example, to show the behaviour, the real data I'm using (that I can't share with you for privacy and protection reasons) is definitely beta distributed, but exhibits exactly the same behaviour...

**Comment by StatMixedML** [comment]
Sorry for the late reply. I would need some time to look into it. I am currently not very responsive.

**Comment by dlewis-esure** [comment]
Hi, no problem - it's not urgent, so take your time!

The output I get is below:

![image](https://user-images.githubusercontent.com/99661156/158570093-95ebf217-9332-4350-94b5-015808c1e1b4.png)

This is the same for both my real data and the dummy example dataset from above.

**Comment by StatMixedML** [comment]
@dlewis-esure I believe I found the problem. It was with the initialization. Can you please try the following:

```python
from sklearn.datasets import load_diabetes
from xgboostlss.model import xgboostlss
from xgboostlss.distributions import Gaussian, Beta
from xgboost import DMatrix
import numpy as np
import pandas as pd
from scipy.special import expit, logit, digamma, polygamma
from scipy.stats import beta

X, y = load_diabetes(return_X_y=True, as_frame=True)


# Rescale y to (0,1)
old_max = np.max(y)
old_min = np.min(y)
new_max = 0.999
new_min = 0.001
OldRange = (old_max - old_min)  
NewRange = (new_max - new_min)  
y_scaled = (((y - np.min(y)) * NewRange) / OldRange) + new_min


train_x = X[:-50]
train_y = y_scaled[:-50]
test_x = X[-50:]
test_y = y_scaled[-50:]
dtrain = DMatrix(train_x, train_y)
dtest = DMatrix(test_x, test_y)


# Adjust initialization
def initialize_beta_workaround(y: np.ndarray):
    """ Function that calculates the starting values, for each distributional parameter individually.
    y: np.ndarray
        Data from which starting values are calculated.
    """
    _, _, loc_fit, scale_fit = beta.fit(y)
    start_values = np.array([loc_fit, scale_fit])

    return start_values

distribution = Beta
distribution.initialize = initialize_beta_workaround
distribution.stabilize = "None"   


# Train Model
single_trial_params = {
    "eta": 0.01,                   
    "max_depth": 4,
    "gamma": 1,
    "subsample": 0.6,
    "colsample_bytree": 0.7,
    "min_child_weight": 1,
}

eval_results = {}
model = xgboostlss.train(
    params=single_trial_params,
    dtrain=dtrain,
    dist=distribution,
    evals=[(dtrain, 'train'), (dtest, 'test')],
    evals_result=eval_results
)
```

**Comment by dlewis-esure** [comment]
Hi, sorry, been absolutely snowed under with work this week - I'll give this a go as soon as I can and get back to you! Really appreciate your speed on this :)

**Comment by dlewis-esure** [comment]
Hi there - sorry this has taken so long, some urgent work popped up that's kept me distracted. Yes, this new initialisation method does do the trick, thank you! I can train a model - now I just need to tune the hyperparameters...

**Comment by StatMixedML** [comment]
Ok nice! Let me know in case you need additional input.  I will also update the beta-distribution accordingly

I close this issue for now.
