### ISSUE TITLE
Bump versions and tag them

### ISSUE THREAD

**Issue by kevinmickey** [StatMixedML/XGBoostLSS#18]
With active development, it may be helpful to bump the version after significant changes, and tag them. This will also help in publishing to pypi.

Let me know if you would like any assistance with this.

**Comment by StatMixedML** [comment]
@kevinmickey Thanks for raising the issue. Very much appreciate your support on this, since I currently find little time to further develop the repo.

**Comment by StatMixedML** [comment]
Closing the issue for now.
