### ISSUE TITLE
Publish to PyPi

### ISSUE THREAD

**Issue by kevinmickey** [StatMixedML/XGBoostLSS#19]
For distribution, it would be very helpful to publish to PyPi. A likely pre-requisite is tagging versions (see #18).

Let me know if you would like any assistance with this.

**Comment by StatMixedML** [comment]
@kevinmickey Thanks for raising the issue. Very much appreciate your support on this, since I currently find little time to further develop the repo.

**Comment by StatMixedML** [comment]
Closing the issue for now.

**Comment by gmgeorg** [comment]
Has there been any updates here for putting this on pypi? @StatMixedML do you plan to do this given the recent uptick in development activity.

**Comment by StatMixedML** [comment]
Yes, having the package on PyPi is still on the ToDo list.

**Comment by minchinweb** [comment]
PyPI link --> https://pypi.org/project/xgboostlss/
