### ISSUE TITLE
Choose values of loc, scale, etc. for norm.ppf

### ISSUE THREAD

**Issue by ahbon123** [StatMixedML/XGBoostLSS#21]
Helllo, may I ask a question regarding **Plot of Actual vs. Predicted Quantiles** part in this link: [https://github.com/StatMixedML/XGBoostLSS/blob/master/examples/simulation_example_Gaussian.ipynb](url),
How could we choose values for loc, scale, etc.?  Thanks.
`norm.ppf(quant_sel[0], loc = 10, scale = 1 + 4*((0.3 < test["x"].values) & (test["x"].values < 0.5)) + 2*(test["x"].values > 0.7))`

**Comment by StatMixedML** [comment]
@ahbon123 Thanks for your interest.

Since you are referring to the simulation example, the data is a simulated Gaussian as follows, where x is the only true feature and all others are noise variables
    # loc = 10
    # scale = 1 + 4*((0.3 < x) & (x < 0.5)) + 2*(x > 0.7)
