### ISSUE TITLE
Support categorical features?

### ISSUE THREAD

**Issue by p-schaefer** [StatMixedML/XGBoostLSS#26]
Does XGBoostLLS support [categorical features](https://xgboost.readthedocs.io/en/stable/tutorials/categorical.html) and [associated hyperparameters](https://xgboost.readthedocs.io/en/stable/parameter.html#cat-param) ?

**Comment by StatMixedML** [comment]
Yes, it supports all functions of the base XGBoost model. However, it currently used XGBoost-Version 1.4.2, so the latest functionality is not yet available.
