### ISSUE TITLE
Cannot Find the Source Code

### ISSUE THREAD

**Issue by houchangtao** [StatMixedML/XGBoostLSS#3]
Hi, this is a great library and I would like to tweak the source code to do my stuff, are you plan to share your source code?

**Comment by StatMixedML** [comment]
Hi houchangtao,

thanks for the interest. Yes I am planning to share the code asap. However, as it is still very developmental and since I can only work on it during my spare time, it might take some time. Hope for your understanding

**Comment by scottfleming** [comment]
Would love to use this package in my research! I've "watch"ed the repo and am looking forward to any updates. Do you have any indication of when it might be publicly available?

In particular, in the "Software Implementations" section of the ReadMe, it says, "In its current implementation, XGBoostLSS is available in R only".  But as far as I can tell it's actually not available in R - am I missing something? If not, could you kindly add Installation instructions to the ReadMe?

**Comment by scottfleming** [comment]
No worries at all! I totally get that you have other constraints on your time, and appreciate the great work you've done on this with whatever spare time you have. "Developmental" is totally fine from my perspective, I'm happy to be a guinea pig and help with debugging/PRs etc. where I can. Even if it's not a package published on CRAN, as long as it's installable via devtools I can work with whatever state it's in.
