### ISSUE TITLE
Support for XGBoost >= 1.6

### ISSUE THREAD

**Issue by rohanp-eiq** [StatMixedML/XGBoostLSS#30]
Would it be possible to support XGBoost 1.6 (or later)? If so, what would be the process of getting that out (can possibly take a look at upgrading it/raising a PR)?

Context is that we have some other dependencies that require XGBoost 1.6 or greater which clashes with the setup.py here.

**Comment by StatMixedML** [comment]
Thanks for your interest in the project.

I am currently working on completely revising the package. I plan to release the new version some timt this month.

**Comment by StatMixedML** [comment]
Closing this with the [new release](https://github.com/StatMixedML/XGBoostLSS/releases).
