### ISSUE TITLE
Loading Models - Losing Information

### ISSUE THREAD

**Issue by fatday** [StatMixedML/XGBoostLSS#31]
When I use joblib to load a model that build by the xgblss, I found that the reloaded model lose some information. The reloaded model will output the different values from the original model even though they have the same input. The difference of the outputs is a constant for all inputs, can you fix this? I think this is because model's attributes get lost after reloading the models.

By the way, is it possible to add quantile regression to the distribution and multitasking learning? I think they are quite useful.

**Comment by StatMixedML** [comment]
Thanks for your interest in the project!

> When I use joblib to load a model that build by the xgblss, I found that the reloaded model lose some information. The reloaded model will output the different values from the original model even though they have the same input. The difference of the outputs is a constant for all inputs, can you fix this? I think this is because model's attributes get lost after reloading the models.

I am working on a revised release of the package, that also includes this fix. Hope to have it out soon

> By the way, is it possible to add quantile regression to the distribution and multitasking learning? I think they are quite useful.

I believe quantile regression is already part of the base XGBoost implementation. So I don't plan to add it. When you say `multitasking learning`, are you referring to modelling several response variables?

**Comment by StatMixedML** [comment]
@fatday Can you check again with the [new release](https://github.com/StatMixedML/XGBoostLSS/releases).

**Comment by StatMixedML** [comment]
Closing this issue.
