### ISSUE TITLE
implement python version 

### ISSUE THREAD

**Issue by Diyago** [StatMixedML/XGBoostLSS#4]

**Comment by StatMixedML** [comment]
Good comment. However, I am currently working on migrating the package to the recently introduced mlr3 package

https://github.com/mlr-org/mlr3

So might take some time until XGBoostLSS is available in python. You might be interested in CatBoostLSS 

https://github.com/StatMixedML/CatBoostLSS

which is very similar to XGBoostLSS, but using CatBoost as a base learner. Still very developmental and given time restrictions, might also take some time to commit the code.

**Comment by cdeterman** [comment]
Was this ultimately implemented in python or is the solution to just use the catboost version?

**Comment by StatMixedML** [comment]
@cdeterman Thanks for your question, although I am not 100% sure what you are referring to. Can you please specify your question in more detail.

**Comment by cdeterman** [comment]
I don't see anything further regarding the python implementation of xgboostlss, only a mention of catboostlss.  I would like to get the python version of xgboostlss.

**Comment by StatMixedML** [comment]
The initial XGBoostLSS implementation was done in R. Once I have the problem of simultaneous parameter estimation across distributional parameter fixed, I will release the R-package. For Python, I am planning to combine both in a new library, where you can chose to fit a model using xgboost / catboost. But that still takes some time.

**Comment by Afaf-Athar** [comment]
Hi, I am trying to install catboosLSS, It throw's this error, actually, I am trying to get a diagnostic plot from the catboost regression model. If anything else we have, can help me regarding plotting?
```
ERROR: Could not find a version that satisfies the requirement catboostlss
ERROR: No matching distribution found for catboostlss`
````

**Comment by ivan-marroquin** [comment]
@StatMixedML 

Thanks for such great package. I am hoping that you will have the opportunity to port this package to Python. 

Ivan
