### ISSUE TITLE
package install

### ISSUE THREAD

**Issue by fipoucat** [StatMixedML/XGBoostLSS#5]
I am asking the procedure to install the package?, used install_github but did not work

**Comment by StatMixedML** [comment]
it is because I am still working on getting it into a package, so there is no code yet pushed to the repo

**Comment by Shafi2016** [comment]
When is expected the availability of your package? Is it possible for you to upload your base codes for your work at this point? It will allow others to test your work too.

**Comment by StatMixedML** [comment]
The thing is that I am still working on getting the package ready, i.e., implementing additional distributions, unit tests and proper documentation. As such, there is no code yet on the repo. I am planning to have it ready by mid-year. I can only work on it during my spare time, so progress is very slow.

**Comment by Shafi2016** [comment]
Thank you so much for the updates. All the best.

**Comment by cdeterman** [comment]
Any updates on installing the R package?  Would love to explore using this package.

**Comment by StatMixedML** [comment]
Kindly referring to https://github.com/StatMixedML/XGBoostLSS/issues/4#issuecomment-632582373.
