### ISSUE TITLE
XGBoostLSS for Julia

### ISSUE THREAD

**Issue by azev77** [StatMixedML/XGBoostLSS#6]
Hi, 
your package & paper look really promising. I can't wait to test drive it. 
The readme mentions a Julia implementation is planned, that would be amazing. 

May I suggest, consider wrapping it in the interface [MLJ](https://github.com/alan-turing-institute/MLJ.jl).jl which already has several boosting & probabilistic forecasting options with more on the way...

**Comment by StatMixedML** [comment]
@azev77 Sorry for the late(ish) reply and thanks for the suggestion.

Yes, I am planning to use the MLJ framework for implementing XGBoostLSS.
