### ISSUE TITLE
SHAP for categorical features 

### ISSUE THREAD

**Issue by p-schaefer** [StatMixedML/XGBoostLSS#70]
I'm getting an error when trying to conduct SHAP interpretations for a model containing categorical features:

```
[18:06:07] WARNING: /workspace/src/c_api/c_api.cc:1240: Saving into deprecated binary model format, please consider using `json` or `ubj`. Model format will default to JSON in XGBoost 2.2 if not specified.
<IPython.core.display.HTML object>
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  xgboost.core.XGBoostError: [18:06:07] /workspace/src/tree/tree_model.cc:899: Check failed: !HasCategoricalSplit(): Please use JSON/UBJSON for saving models with categorical splits.
```

**Comment by StatMixedML** [comment]
This seems to be a native XGBoost / SHAP related issues. Can you please 

- provide a minimum working using XGBoostLSS
- try and re-produce the error using XGBoost directly

Thanks.

**Comment by p-schaefer** [comment]
Yes, sorry it does look like its an issue with XGBoost and Shap directly. 
[https://github.com/shap/shap/issues/2662](https://github.com/shap/shap/issues/2662)
