### ISSUE TITLE
xgboostlss.predict() only gives results for pred_type="parameters"

### ISSUE THREAD

**Issue by TheRealSalmon** [StatMixedML/XGBoostLSS#9]
I'm following the examples. Everything else works correctly but for some strange reason, when I get to the cell where it makes predictions, I always get the output for pred_type="parameters". I would greatly appreciate any help on this matter. 

Thank you!

**Comment by StatMixedML** [comment]
@TheRealSalmon Thanks for raising this issue. Let me look into this and come back to you.

**Comment by StatMixedML** [comment]
@TheRealSalmon Can you please re-try and let me know. Problem should be fixed now.
